build:
  publish: build
  command: npm run build
  functions: functions

plugins:
  - package: '@netlify/plugin-sitemap'
    config:
      dir: build
      baseUrl: ${env:URL, 'https://google.com'}
  - package: ./plugins/orchestrate
    config:
      valueOne: foo
      valueTwo: bar
