build:
  publish: build
  command: npm run build
  functions: functions
  lifecycle:
    onBuild: printenv

plugins:
  - package: '@netlify/plugin-sitemap'
  - package: ./plugins/orchestrate
    config:
      valueOne: foo
      valueTwo: bar
