build:
  publish: build
  command: npm run build && printenv
  functions: functions

plugins:
  - package: '@netlify/plugin-sitemap'
  - package: ./plugins/orchestrate
    config:
      valueOne: foo
      valueTwo: bar
